name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - wordpress/**/composer.lock
      - wordpress/**/package-lock.json
      - .github/workflows/generate-sbom.yml
  push:
    branches:
      - main
    paths:
      - wordpress/**/composer.lock
      - wordpress/**/package-lock.json
      - .github/workflows/generate-sbom.yml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: gc-articles/wordpress
            directory: ./wordpress
            manifest: composer.lock
            type: php
          - component: gc-articles/wordpress/plugin/cds-base
            directory: ./wordpress/wp-content/plugins/cds-base
            manifest: composer.lock
            type: php
          - component: gc-articles/wordpress/plugin/cds-base/frontend
            directory: ./wordpress/wp-content/plugins/cds-base
            manifest: package-lock.json
            type: node
          - component: gc-articles/wordpress/plugin/gc-lists
            directory: ./wordpress/wp-content/plugins/gc-lists
            manifest: composer.lock
            type: php
          - component: gc-articles/wordpress/theme/cds-default
            directory: ./wordpress/wp-content/themes/cds-default
            manifest: composer.lock
            type: php

    steps:
      - name: Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # tag=v2

      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: changes
        with:
          filters: |
            lock: 
              - '${{ matrix.directory }}/${{ matrix.manifest }}'

      - name: Generate ${{ matrix.component }} SBOM
        if: steps.changes.outputs.lock == 'true'
        uses: cds-snc/security-tools/.github/actions/generate-sbom@aa6a6b097e75fd2007aee070b89a8d03c955ac81 # v1
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: ${{ matrix.component }}
          project_type: ${{ matrix.type }}
          working_directory: ${{ matrix.directory }}
